name: Package extension

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        environment: secrets
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install zip
              uses: montudor/action-zip@v1
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  tag_name: autorelease
                  release_name: Automated release ${{ github.run_id }}
                  body: |
                      Release ${{ github.run_id }}
                      Release commit change: "${{ github.event.head_commit.url }}"
                  draft: false
                  prerelease: true
            - name: Zip firefox
              working-directory: firefox
              run: "zip -qq -r firefox.xpi ."
            - name: Zip chrome
              working-directory: chrome
              run: "zip -qq -r chrome.zip ."
            - name: Upload firefox
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: firefox/firefox.xpi
                  asset_name: firefox-unsigned.xpi
                  asset_content_type: application/zip
            - name: Upload chrome
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: chrome/chrome.zip
                  asset_name: chrome.zip
                  asset_content_type: application/zip
